version: '3.8'
services:
  lapdev:
    image: ubuntu:24.04
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/root/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: /bin/bash -c "while sleep 1000; do :; done"
    ports:
      - "8080:8080"  # Web app
      - "5000-5001:5000-5001"  # .NET ports
      - "5037:5037"  # ADB
    environment:
      - DOTNET_ROOT=/usr/share/dotnet
      - ANDROID_HOME=/opt/android-sdk
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: devpassword
      POSTGRES_USER: devuser
      POSTGRES_DB: devdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: