version: '3'
services:
  lapdev:
    image: ubuntu:24.04
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: /bin/bash -c "while sleep 1000; do :; done"
    ports:
      - "8080:8080"
  db:
    image: docker.io/postgres:latest
